### PR TITLE
Remove code

### PR DESCRIPTION
**Pull request by danielpassos**
All of our integration tests for modules are included in the modules project. Before these were a separate project (and a pain to maintain).

### CODE REVIEW

**Comment by matzew** [comment]
+1 on the remove, 

but not sure if the project info here is really adding any value, since all code has been moved out

**Comment by lfryc** [comment]
+1 for remove

yea, project info is not needed here, maybe just a link to the list of repos that contains the integration tests

**Comment by secondsun** [comment]
+1 on remove.  Honestly we can probably delete this repo...
Perhaps add a link to aerogear.org/android?

**Comment by matzew** [comment]
yeah, good call, summers

On Thu, Feb 5, 2015 at 3:32 PM, Hoyt Summers Pittman <
notifications@github.com> wrote:

> +1 on remove. Honestly we can probably delete this repo...
> Perhaps add a link to aerogear.org/android?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-android-integration-tests/pull/30#issuecomment-73054859>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by danielpassos** [comment]
Removed the project info table.

**Pull request merged**
